# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stream_pb2 as stream__pb2


class StreamTesterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNewInfo = channel.unary_stream(
                '/streaming.StreamTester/GetNewInfo',
                request_serializer=stream__pb2.Task.SerializeToString,
                response_deserializer=stream__pb2.Report.FromString,
                )
        self.Ping = channel.unary_unary(
                '/streaming.StreamTester/Ping',
                request_serializer=stream__pb2.Ping_msg.SerializeToString,
                response_deserializer=stream__pb2.Ping_msg.FromString,
                )


class StreamTesterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetNewInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamTesterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNewInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GetNewInfo,
                    request_deserializer=stream__pb2.Task.FromString,
                    response_serializer=stream__pb2.Report.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=stream__pb2.Ping_msg.FromString,
                    response_serializer=stream__pb2.Ping_msg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamTester', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamTester(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetNewInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/streaming.StreamTester/GetNewInfo',
            stream__pb2.Task.SerializeToString,
            stream__pb2.Report.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streaming.StreamTester/Ping',
            stream__pb2.Ping_msg.SerializeToString,
            stream__pb2.Ping_msg.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
