# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='streaming',
  syntax='proto3',
  serialized_options=b'\n\013sr.grpc.genB\016StreamingCOVIDP\001',
  serialized_pb=b'\n\x0cstream.proto\x12\tstreaming\"-\n\x04Task\x12%\n\x08\x64istrict\x18\x01 \x01(\x0e\x32\x13.streaming.District\"^\n\x06Report\x12%\n\x08\x64istrict\x18\x01 \x01(\x0e\x32\x13.streaming.District\x12\x0c\n\x04\x64ied\x18\x02 \x01(\x05\x12\x0b\n\x03ill\x18\x03 \x01(\x05\x12\x12\n\nquarantine\x18\x04 \x01(\x05\"\n\n\x08Ping_msg*\xb7\x02\n\x08\x44istrict\x12\x07\n\x03\x41LL\x10\x00\x12\x0f\n\x0b\x44OLNOSLASKE\x10\x01\x12\x16\n\x12KUJAWSKO_POMORSKIE\x10\x02\x12\r\n\tLUBELSKIE\x10\x03\x12\x0c\n\x08LUBUSKIE\x10\x04\x12\x0b\n\x07LODZKIE\x10\x05\x12\x0f\n\x0bMALOPOLSKIE\x10\x06\x12\x0f\n\x0bMAZOWIECKIE\x10\x07\x12\x0c\n\x08OPOLSKIE\x10\x08\x12\x10\n\x0cPODKARPACKIE\x10\t\x12\r\n\tPODLASKIE\x10\n\x12\r\n\tPOMORSKIE\x10\x0b\x12\x0b\n\x07SLASKIE\x10\x0c\x12\x12\n\x0eSWIETOKRZYSKIE\x10\r\x12\x17\n\x13WARMINSKO_MAZURSKIE\x10\x0e\x12\x11\n\rWIELKOPOLSKIE\x10\x0f\x12\x16\n\x12ZACHODNIOPOMORSKIE\x10\x10\x12\n\n\x06POLAND\x10\x11\x32t\n\x0cStreamTester\x12\x32\n\nGetNewInfo\x12\x0f.streaming.Task\x1a\x11.streaming.Report0\x01\x12\x30\n\x04Ping\x12\x13.streaming.Ping_msg\x1a\x13.streaming.Ping_msgB\x1f\n\x0bsr.grpc.genB\x0eStreamingCOVIDP\x01\x62\x06proto3'
)

_DISTRICT = _descriptor.EnumDescriptor(
  name='District',
  full_name='streaming.District',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOLNOSLASKE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KUJAWSKO_POMORSKIE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LUBELSKIE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LUBUSKIE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LODZKIE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALOPOLSKIE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAZOWIECKIE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPOLSKIE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PODKARPACKIE', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PODLASKIE', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POMORSKIE', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLASKIE', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SWIETOKRZYSKIE', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARMINSKO_MAZURSKIE', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIELKOPOLSKIE', index=15, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZACHODNIOPOMORSKIE', index=16, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLAND', index=17, number=17,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=183,
  serialized_end=494,
)
_sym_db.RegisterEnumDescriptor(_DISTRICT)

District = enum_type_wrapper.EnumTypeWrapper(_DISTRICT)
ALL = 0
DOLNOSLASKE = 1
KUJAWSKO_POMORSKIE = 2
LUBELSKIE = 3
LUBUSKIE = 4
LODZKIE = 5
MALOPOLSKIE = 6
MAZOWIECKIE = 7
OPOLSKIE = 8
PODKARPACKIE = 9
PODLASKIE = 10
POMORSKIE = 11
SLASKIE = 12
SWIETOKRZYSKIE = 13
WARMINSKO_MAZURSKIE = 14
WIELKOPOLSKIE = 15
ZACHODNIOPOMORSKIE = 16
POLAND = 17



_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='streaming.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='district', full_name='streaming.Task.district', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=72,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='streaming.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='district', full_name='streaming.Report.district', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='died', full_name='streaming.Report.died', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ill', full_name='streaming.Report.ill', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quarantine', full_name='streaming.Report.quarantine', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=168,
)


_PING_MSG = _descriptor.Descriptor(
  name='Ping_msg',
  full_name='streaming.Ping_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=180,
)

_TASK.fields_by_name['district'].enum_type = _DISTRICT
_REPORT.fields_by_name['district'].enum_type = _DISTRICT
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['Ping_msg'] = _PING_MSG
DESCRIPTOR.enum_types_by_name['District'] = _DISTRICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:streaming.Task)
  })
_sym_db.RegisterMessage(Task)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:streaming.Report)
  })
_sym_db.RegisterMessage(Report)

Ping_msg = _reflection.GeneratedProtocolMessageType('Ping_msg', (_message.Message,), {
  'DESCRIPTOR' : _PING_MSG,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:streaming.Ping_msg)
  })
_sym_db.RegisterMessage(Ping_msg)


DESCRIPTOR._options = None

_STREAMTESTER = _descriptor.ServiceDescriptor(
  name='StreamTester',
  full_name='streaming.StreamTester',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=496,
  serialized_end=612,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNewInfo',
    full_name='streaming.StreamTester.GetNewInfo',
    index=0,
    containing_service=None,
    input_type=_TASK,
    output_type=_REPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='streaming.StreamTester.Ping',
    index=1,
    containing_service=None,
    input_type=_PING_MSG,
    output_type=_PING_MSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMTESTER)

DESCRIPTOR.services_by_name['StreamTester'] = _STREAMTESTER

# @@protoc_insertion_point(module_scope)
